### ISSUE TITLE
Unable to locate application support path if Title of game includes special signs

### ISSUE THREAD

**Issue by paweljarosz** [Insality/defold-saver#2]
I discovered it because a title in my game.project contains them and it vows an error:

```
ERROR:SCRIPT: saver/saver.lua:82: Unable to locate application support path for "Witchcrafter: Empire Legends": (-21)
````

My proposition to fix it is to modify this line in `M.get_save_path()`:

```
local directory_path = DIRECTORY_PATH
```

to add extraction of signs that are not letters, number or underscore:

```
local directory_path = DIRECTORY_PATH:gsub("%W", "")
```

Or you can even add it above when `DIRECTORY_PATH` is defined.

```
local DIRECTORY_PATH = sys.get_config_string("saver.save_folder", PROJECT_NAME):gsub("%W", "")
```

This addition works in my case.

**Comment by Insality** [comment]
Nice catch, thanks!

**Comment by Insality** [comment]
Fixed in develop
Expose the `saver.save_folder` property to allow not rely on the project title. Apply your solution (with excluding spaces and underscores) on PROJECT_TITLE only
