### ISSUE TITLE
Не сохраняет динамически созданную таблицу в HTML5

### ISSUE THREAD

**Issue by ufgo** [Insality/defold-saver#5]
```
	for i = 1, lvl, 1 do
		table.insert(level, i, { lvl_cell = {} })
		level[i].is_complete = false
		level[i].coins_spent = 0
		level[i].coins_earned = 0
		for j = 1, lvl_cell, 1 do
			table.insert(level[i].lvl_cell, j, {
				is_initialized = false,
				keys = {},
				items = {0,0,0,0,0},
				test_string="string",
				score = 0
			})
		end
	end
saver.bind_save_state("level_data", level)
```

Не сохраняется таблица если создать её динамически и запустить проект в HTML5. (Если запускать с десктопа то ок)

репро: [saver_html_bug.zip](https://github.com/user-attachments/files/17555167/saver_html_bug.zip)

**Comment by Insality** [comment]
Попробуй saver из develop: https://github.com/Insality/defold-saver/archive/refs/heads/develop.zip

Вроде починилось, еще смотрю есть ли какие-то еще проблемы

**Comment by Insality** [comment]
HTML5 version used the json.encode to store the data inside local storage

Problem was with mixing tables (array + dict) or sparse arrays. To escape this now saved using the `sys.serialize` and it should work stable for all the our cases

**Comment by Insality** [comment]
fixed in v3
