### ISSUE TITLE
Saver init nillifies storage data

### ISSUE THREAD

**Issue by boruok** [Insality/defold-saver#6]
I'm not sure that intended behiavour.

```lua
	storage.set("coins", 1000)
	print(storage.get("coins")) -- 1000
	saver.init()
	print(storage.get("coins")) -- nil
```

line:
https://github.com/Insality/defold-saver/blob/aac22850101587a0a8f54827052fea03772dc118/saver/saver.lua#L87

**Comment by Insality** [comment]
Yea, I think it works as intended due the init makes the files load step with all cleaning in case you want to make a soft-reboot in your game
